CREATE TABLE gender
(
    "IdGender" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Gender" VARCHAR(1) NOT NULL
);
CREATE TABLE client
(
    "IdClient" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "LastName" VARCHAR(45) NOT NULL,
    "FirstName" VARCHAR(45) NOT NULL,
    "MiddleName" VARCHAR(45),
    "BirthDay" DATE NOT NULL,
    "Phone" VARCHAR(8) NOT NULL,
    "EMail" VARCHAR(100) NOT NULL,
    "IdGender" INTEGER,
    FOREIGN KEY ("IdGender") REFERENCES Gender ("IdGender")
);
CREATE TABLE manufacturers
(
    "IdManufacturer" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" VARCHAR(100) NOT NULL,
    "StartDateWork" DATE NOT NULL
);
CREATE TABLE producttag
(
    "IdProductTag" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" VARCHAR(45) NOT NULL
);
CREATE TABLE products
(
    "IdProducts" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ProductName" VARCHAR(150) NOT NULL,
    "IdManufacturer" INTEGER,
    "IdProductTag" INTEGER,
    FOREIGN KEY ("IdManufacturer") REFERENCES Manufacturers ("IdManufacturer"),
    FOREIGN KEY ("IdProductTag") REFERENCES ProductTag ("IdProductTag")
);
CREATE TABLE service
(
    "IdServices" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" VARCHAR(45) NOT NULL,
    "Description" VARCHAR(100) NOT NULL,
    "Price" NUMERIC(13,2) NOT NULL CHECK (service."Price" > 0)
);
CREATE TABLE worker
(
    "IdWorker" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "LastName" VARCHAR(45) NOT NULL,
    "FirstName" VARCHAR(45) NOT NULL,
    "MiddleName" VARCHAR(45),
    "BirthDay" DATE NOT NULL,
    "PassportSeriesNumber" VARCHAR(10) NOT NULL,
    "DepartmentCode" VARCHAR(6) NOT NULL,
    "IdGender" INTEGER,
    FOREIGN KEY ("IdGender") REFERENCES Gender ("IdGender")
);
CREATE TABLE purchase_history
(
    "idPurchase_history" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Date" DATE NOT NULL,
    "IdClient" INTEGER,
    "IdProducts" INTEGER,
    "IdServices" INTEGER,
    "IdWorker" INTEGER,
    FOREIGN KEY ("IdClient") REFERENCES Client ("IdClient"),
    FOREIGN KEY ("IdProducts") REFERENCES Products ("IdProducts"),
    FOREIGN KEY ("IdServices") REFERENCES Service ("IdServices"),
    FOREIGN KEY ("IdWorker") REFERENCES Worker ("IdWorker")
);
